# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\tool_gui.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from http.server import BaseHTTPRequestHandler, HTTPServer
from utils import *

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(369, 93)
        MainWindow.setLayoutDirection(QtCore.Qt.RightToLeft)
        MainWindow.setLocale(QtCore.QLocale(QtCore.QLocale.Arabic, QtCore.QLocale.Egypt))
        MainWindow.setDockOptions(QtWidgets.QMainWindow.AllowTabbedDocks|QtWidgets.QMainWindow.AnimatedDocks)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setMinimumSize(QtCore.QSize(369, 0))
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.wordButton = QtWidgets.QPushButton(self.centralwidget)
        self.wordButton.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.wordButton.setFont(font)
        self.wordButton.setObjectName("wordButton")
        self.gridLayout.addWidget(self.wordButton, 0, 0, 1, 1)
        self.convertButton = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.convertButton.setFont(font)
        self.convertButton.setObjectName("convertButton")
        self.gridLayout.addWidget(self.convertButton, 1, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "اداة المعادلات"))
        self.wordButton.setText(_translate("MainWindow", "فتح تطبيق ورد"))
        self.convertButton.setText(_translate("MainWindow", "تحويل صور المعادلات الى لاتيك"))
        self.wordButton.clicked.connect(self.on_wordButton_clicked)
        self.convertButton.clicked.connect(self.on_convertButton_clicked)

    def on_wordButton_clicked(self):
        word_app = open_word()
        get_or_create_document(word_app)
        

        # Pass the word_app to the handler instance
        # handler_instance = MyHandler(word_app)

        with HTTPServer(('', 8000), handler_instance) as server:
            server.serve_forever()        

    def on_convertButton_clicked(self):
        # Code to be executed when the second push button is clicked
        print("Converting equations images to LaTeX...")
        

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())